// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfrwCsKPekZL9CbG68CbSOvctj2t6Uhk',
    appId: '1:365215421238:web:0d427490693e398c889997',
    messagingSenderId: '365215421238',
    projectId: 'gamemate-945aa',
    authDomain: 'gamemate-945aa.firebaseapp.com',
    storageBucket: 'gamemate-945aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD045H1VI1wuHdWXuWYvJKXSfcSLdk6-Dk',
    appId: '1:365215421238:android:f7c1348359c998d4889997',
    messagingSenderId: '365215421238',
    projectId: 'gamemate-945aa',
    storageBucket: 'gamemate-945aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKkLhf1ha9oNuoHqS0c4jCx1MVlnLNFw',
    appId: '1:365215421238:ios:cf44142becd15926889997',
    messagingSenderId: '365215421238',
    projectId: 'gamemate-945aa',
    storageBucket: 'gamemate-945aa.firebasestorage.app',
    iosBundleId: 'com.example.gamemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKkLhf1ha9oNuoHqS0c4jCx1MVlnLNFw',
    appId: '1:365215421238:ios:cf44142becd15926889997',
    messagingSenderId: '365215421238',
    projectId: 'gamemate-945aa',
    storageBucket: 'gamemate-945aa.firebasestorage.app',
    iosBundleId: 'com.example.gamemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRfrwCsKPekZL9CbG68CbSOvctj2t6Uhk',
    appId: '1:365215421238:web:0cd388fc177dfb05889997',
    messagingSenderId: '365215421238',
    projectId: 'gamemate-945aa',
    authDomain: 'gamemate-945aa.firebaseapp.com',
    storageBucket: 'gamemate-945aa.firebasestorage.app',
  );
}
